### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by gofreddo** [HarveyD/react-component-library#66]
I cloned the repo, `npm i` and then `npm run storybook`.  I get : 

```
❯ npm run storybook

> react-component-library@1.0.0 storybook
> start-storybook -p 6006

info @storybook/react v6.5.13
info 
info => Loading presets
info Addon-docs: using MDX1
info => Using PostCSS preset with postcss@7.0.39
info => Using default Webpack4 setup
10% building 1/6 modules 5 active ...te-components/node_modules/@storybook/addon-outline/preview.js-generated-config-entry.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/jeffwilde/code/elevate-components/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jeffwilde/code/elevate-components/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/jeffwilde/code/elevate-components/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/jeffwilde/code/elevate-components/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/jeffwilde/code/elevate-components/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/jeffwilde/code/elevate-components/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/jeffwilde/code/elevate-components/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /Users/jeffwilde/code/elevate-components/node_modules/loader-runner/lib/LoaderRunner.js:205:4 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.0
```

Anyone else seen this?

**Comment by gofreddo** [comment]
I was on Node 18.  It works with node 16.  Probably should add this to the README.md or Engines in package.json
